### ISSUE TITLE
Locate api: incorrect position with rect argument

### ISSUE THREAD

**Issue by AndreasArvidsson** [talonvoice/talon#439]
Today both `locate_hover` and `hover` from `talon.experimental.locate` can accept a `rect` argument. This is very beneficial when you have a screen with high resolution since the time to compute it's much lower if you do it for just the active window instead of the whole screen or screens.

The problem is that the resulting location is relative to the argument rect but used as an absolute position. This is not a huge problem for `hover` since you can just update the result list with the argument rect yourself. `locate_hover` on the other hand moves to an incorrect location if you supply an rect argument. 

The solution is, afaik, just to add the argument rect x/y to the resulting location.

**Comment by lunixbochs** [comment]
should be fixed in 0.2.0-206

**Comment by AndreasArvidsson** [comment]
@lunixbochs It still doesn't quite work. I think the problem is the result isn't centered on the image. Right now the pointer just misses the line compared to my own code below.

rect = argument to locate function
location = return value from locate function
```
x = rect.x + location.x + location.width / 2
y = rect.y + location.y + location.height / 2
```
I believe it's the half width and height that's missing. 

edit:
`locate_hover` seems to have this compensation but not `locate`. Is that by design perhaps?
It behaves the same no matter if you past in the rect argument so I assume it's intentional. I think this is fine since it just locates the image and not the center which of course hover has to do.

**Comment by lunixbochs** [comment]
locate_hover does center on the image
locate does not, because it returns a whole rectangle

**Comment by AndreasArvidsson** [comment]
I realized that for myself. That works really nicely since now I can make an image that starts from a known text or icon and spans all the way to the window delimiter/line. Then a can just use left/top/right/bot from the rectangle to get exact line position. Much better solution than estimating an offset from the rectangle.

It works quite nicely :)
