### ISSUE TITLE
[windows] talon-rust subtitles briefly steal focus

### ISSUE THREAD

**Issue by knausj85** [talonvoice/talon#557]
since all canvases create a window currently in talon-rust, the subtitles ever so briefly steal focus. This can cause problems if there's a brief pause between commands 

Version: 0.3.1-382-g4a86, Branch: rust, OS: Windows-10-10.0.19045

**Comment by lunixbochs** [comment]
should be fixed in latest rust beta, please confirm

**Comment by knausj85** [comment]
From Talon's perspective, it appears the scope change still occurs. This might warrant a separate issue though; no new windows appear in the taskbar now.

- Open Talon Debug menu to the scope option side by side with another app e.g. chrome
- issue a command with subtitles enabled
- observe the scope briefly updates to talon.exe in the Talon Debug menu

**Comment by lunixbochs** [comment]
it it fast enough now that there's no other problem related to the focus change in practice, besides the symptom of the scope flickering?

**Comment by knausj85** [comment]
So far, it seems to be fast enough that it doesn't impact anything; I'll keep an eye on it, particularly under load

**Comment by knausj85** [comment]
I'm afraid this does cause issues, but so far only amongst talon's own windows.

The most reliable:
- open talon debug window
- click into the search field
- issue a command like "word test"
- note the Talon Debug window loses focus for a time, and the search field remains empty.

Following the same steps with subtitles disabled = search field receives expected input. 

Presumably, the subtitles steal the input??

Edit: this ^^ particular issue repros on Mac too

**Comment by lunixbochs** [comment]
this should be fixed in latest talon-rust, can you confirm?
