### ISSUE TITLE
Release notes overflow container when the window first launches

### ISSUE THREAD

**Issue by mirober** [talonvoice/talon#628]
![talon_text](https://github.com/talonvoice/talon/assets/42875462/10d8ec8d-9a36-4e4c-b0d3-4d68c428177e)

Seems to fix itself once the window gets some events

**Comment by lunixbochs** [comment]
That's 630, which was a while ago and I thought I fixed it. Can you repro on 0.4?

**Comment by mirober** [comment]
I'll check the next beta update - I took the screenshot a while ago but have been noticing it in recent versions

**Comment by lunixbochs** [comment]
You can intentionally downgrade to the 0.4 release in the beta channel, as it has an update available already. I'm pretty sure I fixed this right before the final 0.4 release.

**Comment by mirober** [comment]
Still the same

![talon_text](https://github.com/talonvoice/talon/assets/42875462/c8cac4c2-6770-4f76-af38-418ded806535)

**Comment by lunixbochs** [comment]
please check if this still happens when updating from the latest beta (115-0.4.0-167) to any newer version

**Comment by mirober** [comment]
Still happens on a more recent version:

![image](https://github.com/talonvoice/talon/assets/42875462/cc57040a-e8f9-4f5d-acd1-a8b7d9385a19)

**Comment by lunixbochs** [comment]
can you try again on 643?

**Comment by mirober** [comment]
> can you try again on 643?

Yes, seems to be fixed on the latest beta 👍
